### ISSUE TITLE
Can't find snapshots when running test.sh

### ISSUE THREAD

**Issue by rdruss** [openshiftio-vertx-boosters/vertx-cache-booster#31]
[ERROR] Failed to execute goal on project integration-tests: Could not resolve dependencies for project io.openshift.booster:integration-tests:jar:6-SNAPSHOT: The following artifacts could not be resolved: io.openshift.booster:cute-name-service:jar:6-SNAPSHOT, io.openshift.booster:greeting-service:jar:6-SNAPSHOT: Could not find artifact io.openshift.booster:cute-name-service:jar:6-SNAPSHOT in redhat-ga (https://maven.repository.redhat.com/ga/)

If you run mvn install from project root before running mvn verify from the integration-tests directory, then everything works.

**Comment by cescoffier** [comment]
Fixed by #32
