### ISSUE TITLE
too many `.openshiftio` directories

### ISSUE THREAD

**Issue by Ladicek** [openshiftio-vertx-boosters/vertx-cache-booster#4]
The root directory and the `integration-tests` directrory contain `.openshiftio/application.yaml` files that don't make any sense. Processing them results in extraneous build configs and deployment configs in OpenShift, which obviously never materialize, they just fail.

**Comment by cescoffier** [comment]
My mistake, it generated by a script and forgot to remove it.

**Comment by Ladicek** [comment]
There's still an extraneous `.openshiftio/application.yaml` file in the root directory, which shouldn't really be there.
